#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG="/usr/bin/uestc_ct_authclient_monitor.sh"
LOG_FILE="/tmp/uestc_ct_authclient.log"

boot() {
    enabled=$(uci get uestc_ct_authclient.@authclient[0].enabled 2>/dev/null)
    if [ "$enabled" = "1" ]; then
        start
    else
        echo "$(date): 清水河电信认证客户端在配置中被禁用，不启动服务。" >> $LOG_FILE
    fi
}

start_service() {

    sleep 2

    username=$(uci get uestc_ct_authclient.@authclient[0].username 2>/dev/null)
    password=$(uci get uestc_ct_authclient.@authclient[0].password 2>/dev/null)

    if [ -z "$username" ] || [ -z "$password" ]; then
        echo "$(date): 用户名或密码未设置，服务无法启动。" >> $LOG_FILE
        return 1
    fi

    echo "$(date): 服务已启动。" >> $LOG_FILE

    procd_open_instance
    procd_set_param command $PROG
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    echo "$(date): 服务已停止。" >> $LOG_FILE
    # procd 会自动处理停止进程
}

